### ISSUE TITLE
Chapter - Additional modules - Tabulate

### ISSUE THREAD

**Issue by kvaleriy** [natenka/pyneng-book-en#1]
Hi,

Within chapter - Additional modules - Tabulate (https://pyneng.readthedocs.io/ru/latest/book/12_useful_modules/tabulate.html) found an issue with tabulate. Here is my code:
from tabulate import tabulate

data = {{'IP': '15.0.15.1',
  'Interface': 'FastEthernet0/0',
  'Protocol': 'up',
  'Status': 'up'
         },
 {'IP': '10.0.12.1',
  'Interface': 'FastEthernet0/1',
  'Protocol': 'up',
  'Status': 'up'},
 {'IP': '10.0.13.1',
  'Interface': 'FastEthernet0/2',
  'Protocol': 'up',
  'Status': 'up'},
 {'IP': '10.1.1.1',
  'Interface': 'Loopback0',
  'Protocol': 'up',
  'Status': 'up'},
 {'IP': '100.0.0.1',
  'Interface': 'Loopback100',
  'Protocol': 'up',
  'Status': 'up'}}

print(tabulate(data, headers='key'))

Traceback (most recent call last):
  File "/Users/Retina/PycharmProjects/python-start/Play.py", line 3, in <module>
    data = {{'IP': '15.0.15.1',
TypeError: unhashable type: 'dict'

May be something wrong with example or with my script?

**Comment by natenka** [comment]
This issue is not related to tabulate. You have created a set with dictionaries. The elements of a set must be immutable object: number, string, tuple. 
You need to create a list or tuple of dictionaries (square brakets or parentheses), then everything will work

```
data = [{'IP': '15.0.15.1',
'Interface': 'FastEthernet0/0',
'Protocol': 'up',
'Status': 'up'
},
{'IP': '10.0.12.1',
'Interface': 'FastEthernet0/1',
'Protocol': 'up',
'Status': 'up'},
{'IP': '100.0.0.1',
'Interface': 'Loopback100',
'Protocol': 'up',
'Status': 'up'}]

print(tabulate(data, headers='key'))
```

**Comment by kvaleriy** [comment]
Still it returns error:
Traceback (most recent call last):
  File "/Users/Retina/PycharmProjects/python-start/Play.py", line 17, in <module>
    print(tabulate(data, headers='key'))
  File "/Users/Retina/Library/Python/3.8/lib/python/site-packages/tabulate.py", line 1426, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/Users/Retina/Library/Python/3.8/lib/python/site-packages/tabulate.py", line 1073, in _normalize_tabular_data
    raise ValueError(
ValueError: headers for a list of dicts is not a dict or a keyword

**Comment by natenka** [comment]
```
headers='keys')
```
![Screenshot 2020-11-11 165041](https://user-images.githubusercontent.com/15850513/98826253-23ac5180-243e-11eb-97bb-635bb91103cc.png)

**Comment by kvaleriy** [comment]
You are right, sorry for bothering with typo.

By the way your book is quit good!
